version: "3"
services:
  nginx:
    image: tool_nginx:1.17.9
    container_name : tool_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - mysql
    volumes:
      - D:/develop/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - D:/develop/data/nginx/conf.d:/etc/nginx/conf.d
      - D:/develop/data/nginx/log:/var/log/nginx
    networks:
      - webnet
  mysql:
    image: tool_mysql:8.0.19
    container_name: tool_mysql
    restart: always
    environment:
      - TZ=CST-8
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - D:/develop/data/mysql/data:/var/lib/mysql
      - D:/develop/data/mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: tool_redis:5.0.7
    container_name: tool_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - D:/develop/data/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - D:/develop/data/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
networks:
  webnet:
