# 开发环境
server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tool_gxlirong_com?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        enabled: true

  redis:
    host: localhost
    port: 6379
    password: 67af138483b0fac3a10ea3abe445e91978b41effd37dc51ebc71a50325f0d50a
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: a59360b37f20bb9ce22710a4ff3a2b6fff5aff51b3ac1aa989687d59fcecbb83
file:
  upload:
    file-temp-path: C:/Users/gtppo/Desktop/gxlirong/tool.gxlirong.com/www/backend/temp/
    minecraft-mod-file-path: D:/Game/我的世界服务器/1.12.2版本/mods/
    minecraft-file-path: C:/Users/gtppo/Desktop/gxlirong/tool.gxlirong.com/www/backend/file/minecraftMod/
    file-path: C:/Users/gtppo/Desktop/gxlirong/tool.gxlirong.com/www/backend/file/
