# 发布环境
server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tool_gxlirong_com?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: tool
    password: 328acc9dd677cf783ecdf7e57c6eff20b9d57ecd9dafb4925a0c99aafb9cb171
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        enabled: true

  redis:
    # 服务器IP地址
    host: 127.0.0.1
    # 连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password:
    # 使用库
    database: 1

file:
  upload:
    file-temp-path: /usr/local/docker/www/temp
